<script>
var pwdregex = <?php echo json_encode($this->pwdfieldmatch); ?>;
var pwdlength = <?php echo json_encode($this->pwdfieldlength); ?>;
var pwdminlength = <?php echo json_encode($this->pwdminlength); ?>;
</script>

<div id="authWrapper">
    <?php if(isset($this->headlineHTML)) echo $this->headlineHTML; ?>
    <div id="formWrapper" class="sideBarImageBorder">
        <form id="authLogin" name="authLogin" method="post" class="loginForm contentBgColor clearfix" action="/auth/dochangepassword" autocomplete="off">
            <fieldset id="formFieldset">
                <?php if(isset($this->siteConfigs['PasswordHelp']) && $this->siteConfigs['PasswordHelp'] == 't'){?>
                    <p class="resetPass contentTextIcons"><b><?php if (isset($this->passwdinstructions) && !empty($this->passwdinstructions)) { echo $this->passwdinstructions; } ?> </b> </p>
                <?php } ?>
                <p class="messageField <? if(isset($this->errMsg)){echo 'errorMessage red';} ?>" <? if(isset($this->errMsg)){echo 'style="display: block;"';} ?>>
                    <? if(isset($this->errMsg)){ echo '<i class="fa '. $this->iconClass.'"></i>'; } ?>
                    <?php if(isset($this->errMsg)){ echo $this->errMsg; } ?>
                </p>
                <? if($this->key != 'invalid'){ ?>
                <p class="formField contentTextIcons">
                    <label for="username"><?= $this->siteLabels['UserName']; ?>:</label>
                    <input type="text" id="username" name="username" placeholder="<?= $this->siteLabels['UserName']; ?>" />
                </p>
                <p class="formField contentTextIcons">
                    <label for="newPassword"><?= $this->siteLabels['NewPassword']; ?>:</label>
                    <input type="password" id="newPassword" name="newPassword" placeholder="<?= $this->siteLabels['NewPassword']; ?>" />
                </p>
                <p class="formField contentTextIcons">
                    <label for="rePassword"><?= $this->siteLabels['RepeatPassword']; ?>:</label>
                    <input type="password" id="rePassword" name="rePassword" placeholder="<?= $this->siteLabels['RepeatPassword']; ?>" />
                </p>
                <? } ?>
            </fieldset>
            <? if($this->key != 'invalid'){ ?>
            <p id="message" class="contentTextIcons"><?= $this->siteLabels['ChangePasswordMsg']; ?></p>
            <input type="hidden" name="key" value="<?= $this->key; ?>" />
            <div class="loginBtns clearfix">
            	<button id="authSubmit" class="customButton"><?= $this->siteLabels['ChangePassword']; ?></button>
            </div>
            <? } ?>
        </form>
    </div>
    <div class="helpLinks">
        <p id="forgotAuthWrapper">
            <a href="/auth/forgotpassword" id="authForgot" class="primaryTextIcons" title="<?= $this->siteLabels['ForgotPassTitle']; ?>"><?= $this->siteLabels['ForgotPass']; ?></a>
            <span class="primaryTextIcons">  |  </span>
            <a class="help primaryTextIcons" href="/help/UserGuide/Catalyst_LoginHelp_<?= $this->siteConfigs['DefaultLanguage']?>.pdf" title="<?= $this->siteLabels['NavHelp']; ?>" target="_blank"><?= $this->siteLabels['NavHelp']; ?></a> 
        </p>
    </div>
</div>
