<div id="authWrapper">
    <?php if(isset($this->headlineHTML)) echo $this->headlineHTML; ?>
    <div id="formWrapper" class="sideBarImageBorder">
        <form id="forgotPassLogin" name="forgotPassLogin" method="post" class="loginForm contentBgColor clearfix" action="/auth/doforgotpassword" autocomplete="off">
            <fieldset id="formFieldset">
                <p class="messageField <? if(!isset($this->errMsg) && !isset($this->sysMsg)){echo ""; } else if(isset($this->errMsg)){ echo "errorMessage"; } else if(isset($this->sysMsg)){ echo "systemMessage"; } ?>">
                <? if(isset($this->sysMsg)){ ?>
                <i class="fa <?= $this->iconClass; ?>"></i>
                <? } ?>
                <? if(isset($this->errMsg)){ echo $this->errMsg; } else if(isset($this->sysMsg)){ echo $this->sysMsg; } ?></p>
                <p class="formField contentTextIcons">
                    <label for="username"><?= $this->siteLabels['UserName']; ?>:</label>
                    <input type="text" id="username" name="username" placeholder="<?= $this->siteLabels['UserName']; ?>" />
                </p>
                <p class="contentTextIcons orField">-- <?= $this->siteLabels['Or']; ?> --</p>
                <p class="formField contentTextIcons">
                    <label for="email"><?= $this->siteLabels['Email']; ?>:</label>
                    <input type="text" id="email" name="email" placeholder="<?= $this->siteLabels['Email']; ?>" />
                </p>
            </fieldset>
            <p id="message" class="contentTextIcons"><?= $this->siteInfo['ForgotPasswordMsg']; ?></p>
            <input type="hidden" name="submitx" />
            <div class="loginBtns clearfix">
                <button id="authSubmit" class="customButton"><?= $this->siteLabels['resetmypassword']; ?></button>
            </div>
        </form>
    </div>
    <div class="helpLinks">
        <p id="forgotAuthWrapper">
            <a class="help primaryTextIcons" href="/help/UserGuide/Catalyst_LoginHelp_<?= $this->siteConfigs['DefaultLanguage']?>.pdf" title="<?= $this->siteLabels['NavHelp']; ?>" target="_blank"><?= $this->siteLabels['NavHelp']; ?></a> 
        </p>
    </div>
</div>