<? $oldPassClass = isset($this->errMsg) ? 'errorField' : ''; ?>


<div id="authWrapper">
    <?php if(isset($this->headlineHTML)) echo $this->headlineHTML; ?>
    <div id="formWrapper" class="sideBarImageBorder">
<script>
var pwdregex = <?php echo json_encode($this->pwdfieldmatch); ?>;
var pwdlength = <?php echo json_encode($this->pwdfieldlength); ?>;
var pwdminlength = <?php echo json_encode($this->pwdminlength); ?>;
</script>
        
<form id="resetPassLogin" name="resetPassLogin" method="post" class="loginForm contentBgColor clearfix" action="/auth/doresetpassword" autocomplete="off">
            <fieldset id="formFieldset">
                <?php if(isset($this->siteConfigs['PasswordHelp']) && $this->siteConfigs['PasswordHelp'] == 't'){?>
                    <p class="resetPass contentTextIcons"><b><?php if (isset($this->passwdinstructions) && !empty($this->passwdinstructions)) { echo $this->passwdinstructions; } ?> </b> </p>
                <?php } ?>
                <p class="messageField <? if(isset($this->errMsg)){echo 'errorMessage red';} ?>" <? if(isset($this->errMsg)){echo 'style="display: block;"';} ?>>
                    <? if(isset($this->errMsg)){ echo '<i class="fa '. $this->iconClass.'"></i>'; } ?>
                    <?php if(isset($this->errMsg)){ echo $this->errMsg; } ?>
                </p>
                <p class="formField contentTextIcons">
                    <label for="oldPass"><?= $this->siteLabels['OldPassword']; ?>:</label>
                    <input type="password" id="oldPass" name="oldPass" class="<?= $oldPassClass; ?>" placeholder="<?= $this->siteLabels['OldPassword']; ?>" />
                </p>
                <p class="formField contentTextIcons">
                    <label for="newPass"><?= $this->siteLabels['NewPassword']; ?>:</label>
                    <input type="password" id="newPass" name="newPass" placeholder="<?= $this->siteLabels['NewPassword']; ?>" />
                </p>
                <p class="formField contentTextIcons">
                    <label for="confirmPass"><?= $this->siteLabels['ConfirmNewPassword']; ?>:</label>
                    <input type="password" id="confirmPass" name="confirmPass" placeholder="<?= $this->siteLabels['ConfirmNewPassword']; ?>" />
                </p>
            </fieldset>
            <p id="message" class="contentTextIcons"><?= $this->siteLabels['ResetPasswordMsg']; ?></p>
            <div class="loginBtns clearfix">
            	<button id="resetPassSubmit" class="customButton"><?= $this->siteLabels['ResetPassword']; ?></button>
            </div>
        </form>
    </div>
    <div class="helpLinks">
        <p id="forgotAuthWrapper">
            <a href="/auth/forgotpassword" id="authForgot" class="primaryTextIcons" title="<?= $this->siteLabels['ForgotPassTitle']; ?>"><?= $this->siteLabels['ForgotPass']; ?></a>
            <span class="primaryTextIcons">  |  </span>
            <a class="help primaryTextIcons" href="/help/UserGuide/Catalyst_LoginHelp_<?= $this->siteConfigs['DefaultLanguage']?>.pdf" title="<?= $this->siteLabels['NavHelp']; ?>" target="_blank"><?= $this->siteLabels['NavHelp']; ?></a> 
        </p>
    </div>
</div>
