<div id="authWrapper" class="">
    <?php if(isset($this->headlineHTML)) echo $this->headlineHTML; ?>
    <div id="formWrapper" class="sideBarImageBorder">
        <form id="regAuthLogin" name="regAuthLogin" method="post" class="loginForm contentBgColor clearfix" action="/auth/doSelfRegLogin" autocomplete="off">
            <fieldset id="formFieldset">
                <div id="msgReg"></div>
				<div class="instrText">
                    <h4 class="contentTextIcons"><?= $this->siteLabels['NewUserReg']; ?></h4>
                    <p class="contentTextIcons"><?= $this->siteLabels['PleaseEnterSitePWD']; ?></p>
                </div>
                <p class="formField contentTextIcons">
                    <label for="password"><?= $this->siteLabels['SitePassword']; ?>:</label>
                    <input type="password" id="regPassword" class="<? if(isset($this->errMsg)) echo "errorField" ?>" name="regPassword" placeholder="<?= $this->siteLabels['SitePassword']; ?>"/>
                </p>
            </fieldset>
            <div class="loginBtns clearfix">
                <input type="hidden" name="submitx" />
                <p class="selfRegLaunch">
                    <button id="regSubmit" class="customButton"> <?= $this->siteLabels['Continue']; ?></button>
                </p>
                <p class="loginBtn">
                    <button id="regCancelBtn" class="customSecondaryBtn"><?= $this->siteLabels['Cancel']; ?></button>
                </p>
            </div>
        </form>
    </div>
</div>