		<div id="console-statusbar-container" style="width: 100%; height: 174px; overflow: auto; position:absolute;top:0px;left:0px;">
			<div id="console-statusbar-content" class="console-statusbar">
					<div id="p-69-box-714-box-45" style="width: 716px; height: 174px; float:left;  ">
						<img src="<?php echo CDN_IMG_URL ?>/images/promotional-2.png" width="100%" height="100%">
					</div>
					<div id="p-69-box-714-box-46" style="width: 716px; height: 174px; float:left;  ">
						<img src="<?php echo CDN_IMG_URL ?>/images/promotional-3.png" width="100%" height="100%">
					</div>
					<div id="p-69-box-714-box-47" style="width: 716px; height: 174px; float:left; ">
						<img src="<?php echo CDN_IMG_URL ?>/images/promotional-4.png" width="100%" height="100%">
					</div>
					<div id="p-69-box-714-box-48" style="width: 716px; height: 174px; float:left;  ">
						<img src="<?php echo CDN_IMG_URL ?>/images/promotional-1.png" width="100%" height="100%">
					</div>
			</div>
		</div>
	<script type="text/javascript">
		var statusbarScroll = new iScroll("console-statusbar-container");
	</script>