<li>
    <? if(in_array('queue', $this->currentLoc)){ ?>
		<a class="currentCrumb"><?= $this->siteLabels['MyQueue']; ?></a>
	<? } ?>
	
	<? if(in_array('preview', $this->currentLoc)){ ?>
	    <a href="/learn/queue" class="previousCrumb"><?= $this->siteLabels['MyQueue']; ?></a>
	    <a class="currentCrumb"><?= $this->siteLabels['ModulePreview']; ?></a>
	<? } ?>
    	
	<? if(in_array('viewcertificate', $this->currentLoc)){ ?>
	    <a href="/learn/queue" class="previousCrumb"><?= $this->siteLabels['MyQueue']; ?></a>
	    <a class="currentCrumb"><?= $this->siteLabels['Certification']; ?></a>
	<? } ?>
	
	
	<? if(in_array('profile', $this->currentLoc)){ ?>
		<a href="/learn/queue" class="previousCrumb"><?= $this->siteLabels['MyQueue']; ?></a>
		<a class="currentCrumb"><?= $this->siteLabels['NavProfile']; ?></a>
	<? } ?>
	
	<? if(in_array('history', $this->currentLoc)){ ?>
		<a href="/learn/queue" class="previousCrumb"><?= $this->siteLabels['MyQueue']; ?></a>
		<a class="currentCrumb"><?= $this->siteLabels['NavHistory']; ?></a>
	<? } ?>
	
	<? if(in_array('admin', $this->currentLoc)){ ?>
		<a href="/learn/queue" class="previousCrumb"><?= $this->siteLabels['MyQueue']; ?></a>
		<a class="currentCrumb"><?= $this->siteLabels['NavAdmin']; ?></a>
	<? } ?>
</li>