<?= $this->doctype(); ?>
<html>
<head>
	<?= $this->headTitle(); ?>
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
    <?= $this->headLink(); ?>
    <style type="text/css">
		<?= $this->cssStr; ?>
	</style>
    
    <?= $this->headScript(); ?>
   
    <script type="text/javascript" >
		$(document).ready(function(){
			<?= $this->docReadyJS; ?>
		});
    </script>
</head>
<body>
    <div id="wrapper">
        <?= $this->render('common/header.phtml'); ?>

        <div id="content">
		    <?= $this->layout()->content; ?>
		</div>
        <div id="fspace"></div>
    </div>
    <div id="footer">
        <?= $this->render('common/footer.phtml'); ?>
    </div>
</body>
</html>