<?php
    if(!isset($this->contentSubNav))
        $this->contentSubNav = '';
    if(!isset($this->leftColumnContent))
        $this->leftColumnContent = '';
    if(!isset($this->footerFile))
        $this->footerFile = 'common/footer.phtml';
?>

<?= $this->doctype(); ?>
<html>
<head>
	<?= $this->headTitle(); ?>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta id="viewport" name="viewport" content="initial-scale=1; user-scalable=1; minimum-scale=1; maximum-scale=1" />
	<link rel="shortcut icon" type="image/x-icon" href="/custom_files/<?=$this->siteName?>.ico?t=<?=mktime()?>" />
	
	<?= $this->headLink(); ?>
	<style type="text/css">
		<?= $this->cssStr; ?>
	</style>
	<?= $this->headStyle(); ?>
    <?= $this->headScript(); ?>
    
    <script type="text/javascript">
		$(document).ready(function(){
			<?= $this->docReadyJS; ?>
		});
    </script>
</head>
<body>
<div id="wrapper" class="legacy_layout">
    <div id="container" class="oneColumn">
        <?= $this->render('common/header.phtml'); ?>

        <div id="centerWrapper">
            <div id="contentWrapper">
    			<?= $this->contentSubNav; ?>
    			<div id="contentBuffer">
    				<div id="contentBody">
    				    <?= $this->layout()->content; ?>
    				</div>
    			</div>
    		</div>
        </div>
        <div id="footer">
            <?= $this->render('common/footer_noRefresh.phtml'); ?>
        </div>
    </div>
</div>    
</body>
</html>
<!--#### legacy_layout.phtml ####-->