<!-- <?=$this->siteName?> -->
<?php
	if(!isset($this->colClass))
		$this->colClass = 'imgView';
    if(!isset($this->rightColumnContent))
        $this->rightColumnContent = '';
    if(!isset($this->footerFile))
        $this->footerFile = 'common/footer.phtml';
?>
<?= $this->doctype(); ?>
<html>
    <head>
        <?= $this->headTitle(); ?>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=1" name="viewport"/>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="shortcut icon" type="image/x-icon" href="/custom_files/<?=$this->siteName?>.ico?t=<?=mktime()?>" />
        <?= $this->headLink(); ?>

        <style type="text/css">
            <?= $this->cssStr; ?>
        </style>

        <?= $this->headStyle(); ?>
        <?= $this->headScript(); ?>
        <script type="text/javascript">jwplayer.key="4a6Y+XobzCyBjjz1hSrM3odEU6CZueg6aresRQ==";</script>
        <script type="text/javascript">
            $(document).ready(function(){
                <?= $this->docReadyJS; ?>
            });
        </script>
        <link href="<?=$this->customCSSFile?>" media="screen" rel="stylesheet" type="text/css">
    </head>
    <body class="globalBgColor">
    <!-- THREE COLUMN LAYOUT --> 
        <?= $this->render('common/header.phtml'); ?>
        <div class="container clearfix">
            <?= $this->render('common/sub_header.phtml'); ?>
            <div id="contentWrapper" class="clearfix row col-lg-12">
               <?= $this->render('common/left_menu.phtml'); ?>
               <div id="mainContent" role="main" class="middle col-lg-8 col-md-8 col-xs-12">
                 <?= $this->render('common/page_content_header.phtml'); ?>
                 <div class="content clearfix borders contentBgColor container-fluid">
                     <?= $this->layout()->content; ?>
                 </div>
               </div>
               <div id="rightColumn" class="sideBar col-lg-2 col-md-2 hidden-xs ">
                  <?= $this->render('common/right_column.phtml'); ?>
               </div>
            </div>
        </div>
        <?= $this->render($this->footerFile); ?>
        <?= $this->languageConfirmForm($this->siteConfigs, $this->siteLangs, $this->siteLabels,  array('userProfileLangVal' => $this->userProfileLangVal, 'siteDefLang' => $this->siteDefLang));?>
    </body>
</html>
