                        <!--- START ERROR CONTENT --->
                        <div id="errorWrapper">
                            <!--- START ERROR TOP SECTION --->
                            <div id="errorTop">
                                <p class="messageTop"><span><?= $this->sorryMsg ?></span><br><?= $this->topMsg ?></p>
                            </div>
                            <!--- END ERROR TOP SECTION --->
                            <!--- START ERROR BOTTOM SECTION --->
                            <div id="errorBottom">
                                <p class="messageBottom"><?= $this->botMsg ?></p>
                            </div>
                            <!--- END ERROR BOTTOM SECTION --->
                        </div>
                        <!--- END  ERROR CONTENT --->

