<div id="backBtnWrapper">
    <a href="#">Back</a>
    <div class="bg"></div>
</div>

<div id="previewWrapper" class="columnWrapper">
    <div id="graphicWrapper" class="column opaqueColumn oneThirdColumn">
        <p class="length">Approx. 10min to complete</p>
    </div>
    <div id="infoWrapper" class="column twoFifthColumn">
        <h2>Component Title</h2>
        <ul>
            <li><a href="#" class="close">Close</a></li>
            <li><a href="#" class="module">Category Type</a></li>
        </ul>
        <div class="desc">Component Description</div>
        <button class="start">start now</button>
    </div>
    <div id="remindWrapper" class="column quarterColumn">
        <div class="partnerBranding">Partner Branding</div>
        <p class="dueDate">due In 3 Days</p>
        <p>
            <select id="language">
                <option value="International">International</option>
            </select>
        </p>
    </div>
</div>

