<div id="surveycontent">


<table width="95%" cellspacing="0" cellpadding="0">
          <tr>
               <td colspan="2"><img src="<?php echo CDN_IMG_URL ?>/images/survey.jpg"></td>
          </tr>
           <tr>
               <td colspan="2">&nbsp; </td>
          </tr>
          <tr>
              <td class="spacing">&nbsp;</td>
              <td id="survey">
                 
         
              </td>
              <td class="spacing">&nbsp;</td>
             
             
         </tr>
         <tr>
         	<td colspan="2">
     			<br>
                 <input id="surveyclose" type="submit" value="Close">
             </td>
         </tr>

</table>


</div>

