<div id="surveycontent">


<table width="95%" cellspacing="0" cellpadding="0">
          <tr>
               <td colspan="2"><img src="<?php echo CDN_IMG_URL ?>/images/survey.jpg"></td>
          </tr>
           <tr>
               <td colspan="2">&nbsp; </td>
          </tr>
          <tr>
              <td class="spacing">&nbsp;</td>
              <td id="survey">
                 <table width="100%">
                    <tr>
                      <td   colspan="2" id="survey-summary" class="survey_summary">
                       <!-- Summary text wil come here -->
                      </td>
                    </tr>
                    <tr>
                      <td>&nbsp;</td>
                    </tr>
                    <tr>
                     <td colspan="2" id="survey-quesetions"> </td>
                    </tr>
                    <tr>
                       <td   colspan="2" >
                            <input id="surveysubmit" type="submit" value="Submit">
                       </td>
                   </tr>
                 </table>
         
              </td>
              <td class="spacing">&nbsp;</td>
         </tr>

</table>


</div>

