<!DOCTYPE html>
<html>
<head>
	<title>Catalyst / AIM Integration</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/_aim_core.css">
</head>
<body>
	<nav>
		<ul>
			<li class="userName">Welcome, Deepak Crowley</li>
			<li><a href="#" class="selected">Admin Tools</a></li>
			<li><a href="#">My Page</a></li>
			<li><a href="#">My Profile</a></li>
			<li><a href="#">Help</a></li>
			<li><a href="#">Sign Out</a></li>
		</ul>
	</nav>
	<div class="banner">
		<img src="images/banner.png" alt="AIM Banner" >
	</div>
	<div id="container">
		<div class="contentWrapper">
			<h3>Survey Manager</h3>
			<div class="surveyManager">
				<section class="buildSurvey">
					<h3><span class="arrowIcon"></span>Build a Survey</h3>
					<p> Click <strong>Create a Survey</strong> to start building a new survey.</p>
					<button type="button" class="mainBtn">Create a Survey</button>
				</section>
				<section class="surveySection">
					<h3><span class="arrowIcon"></span>Surveys</h3>
					<div class="surveyWrap">
						<p class="surveysFound">7 results found</p>
						<ul>
							<li><a href id="surveyNameHdr">Survey Name</a></li>
							<li><a href id="statusHdr">Status</a></li>
						</ul>
						<div class="surveys">
							<p class="surveyName"><a href="#">qatracking06 C Survey 1385</a></p>
							<p class="surveyStatus">Draft</p>
							<p class="surveyName"><a href="#">qatracking06 C Survey 1386</a></p>
							<p class="surveyStatus">Draft</p>
							<p class="surveyName"><a href="#">qatracking06 C Survey 1387</a></p>
							<p class="surveyStatus">Published</p>
							<!-- .cf should remain at bottom of list to clear the div. -->
							<div class="cf"></div>
						</div>
					</div>
					<div class="cf"></div>
				</section>
			</div>
		<footer>
			<a href="http://lrn.com" target="_blank"><img src="images/powered-by-lrn.gif" class="fFloat" alt="Powered by LRN" ></a>
			<p class="fFloat"> LRN Copyright | <a href="http://lrn.com/privacy.html" target="_blank">LRN Privacy Statement</a></p>
			<a href="https://privacy-policy.truste.com/click-with-confidence/wps/em/www.lrn.com/seal_m" target="c"><img src="images/trust-e.png" class="fFloat" alt="TRUSTe Certified Privacy" ></a>
		</footer>
		</div>
	</div>
</body>
</html>