<script>
var pwdregex = <?php echo json_encode($this->pwdfieldmatch); ?>;
var pwdlength = <?php echo json_encode($this->pwdfieldlength); ?>;
var pwdminlength = <?php echo json_encode($this->pwdminlength); ?>;
var siteErrors = <?php echo json_encode($this->siteErrors); ?>;

// override default title for this page
document.title = "<?= $this->siteLabels['ChangeYourPassword']; ?>";
</script>
<script>
        $(document).ready(function(){                    
            $(".profileInfo").find('h3').focus();
        });
</script>
<?php if(isset($this->siteConfigs['PasswordHelp']) && $this->siteConfigs['PasswordHelp'] == 't' && $this->siteConfigs['UserToolDisablePassword'] != 't'){?>
    <section class="changeProfile" id="slide_3">
    	<div class="profileInfo borderBottomThin">
    		<h3 tabindex="0" class="contentTitles"><?= $this->siteLabels['ChangeYourPassword']; ?></h3>
    		<p  tabindex="0" class="contentTextIcons"><?php if (isset($this->passwdinstructions) && !empty($this->passwdinstructions)) { echo htmlspecialchars($this->passwdinstructions); } ?> </p>
    	</div>
        <div class="profileDetails changePass" tabindex="0">
    	                <p class="<? if(isset($this->errMsg)){ echo "errorMessage"; } else if(isset($this->sysMsg)){ echo "systemMessage"; } ?>"><span></span><? if(isset($this->errMsg)){ echo $this->errMsg; } else if(isset($this->sysMsg)){ echo $this->sysMsg; }?></p>
    		<div class="theDetails secondaryBgColor">
                    <form id="changePassForm" name="changePassForm" action="/profile/updatepassword" method="post" autocomplete="off">
    				<p class="changePassSection contentTextIcons clearfix" id="curPasField">
                                    <sup><span class="required">*</span></sup><label for="currentPass" class="titles"><?= $this->siteLabels['CurrentPassword']; ?>:</label>
                                    <input aria-required="true" type="password" id="currentPass" name="currentPass" tabindex="0" placeholder="<?= $this->siteLabels['CurrentPassword']; ?>">
    				</p>
    				<p class="changePassSection contentTextIcons clearfix" id="newPasField">
                                   <sup><span class="required">*</span></sup><label for="newPass" class="titles"><?= $this->siteLabels['NewPassword']; ?>:</label>
    					<input aria-required="true" type="password" id="newPass" name="newPass" tabindex="0" placeholder="<?= $this->siteLabels['NewPassword']; ?>">
    				</p>
    				<p class="changePassSection contentTextIcons clearfix" id="confirmPasField">
                                    <sup><span class="required">*</span></sup><label for="confirmPass" class="titles"><?= $this->siteLabels['Confirmpassword']; ?>:</label>
    					<input aria-required="true" type="password" id="confirmPass" name="confirmPass" tabindex="0" placeholder="<?= $this->siteLabels['Confirmpassword']; ?>">
    				</p>
    				<div class="updateButtons">
						<button role="button" type="submit" id="changePassFormSubmit" class="changePassFormSubmit customButton"><?= $this->siteLabels['Save']; ?></button>
                        <button role="button" type="reset" id="editCancelBtn" class="customSecondaryBtn"><?= $this->siteLabels['Cancel']; ?></button>
			        </div>
    			</form>
    		</div>
    	</div>
    </section>
<?php }?>

