<div class="columnWrapper">
    <div class="column opaqueColumn halfColumn">
        <h3>Social</h3>
        <?$this->chatter = "enabled"; ?>
        <? if ($this->chatter == "enabled") {?>
        <div class="profileSection">
            <p class="sectionIcon main"></p>
            <div class="profileInfo">
            <p class="infoSection">
                This will be changed. This is only to add Chatter to your profile.
                <button class="social chatter" id="chatter">Add Chatter to your profile</button>
            </p>

            </div>
            
        </div>
        <?php }?>
    </div>
</div>