<div id="previewWrapper" class="columnWrapper">
	<div id="noChannelPanel" class="column twoFifthColumn"><p>
		<div id="mqItemWrap" class="group">
                    <form method="post" action="/chatter/signin" id="form" autocomplete="off">
				<fieldset><label for="email"><?= $this->siteLabels['Email']; ?></label>: <input type="text" name="email" id="email"></fieldset>
				<fieldset><label for="email"><?= $this->siteLabels['Password']; ?></label>: <input type="password" name="password" id="password"></fieldset>
				<button name="submit" id="chatterSubmit" class="customButtom">Log In</button>
			</form>
			<div id="response"></div>
		</div>
	</p></div>
</div>