<hgroup class="adminHeader">
	<h2>Module configuration</h2>
</hgroup>
<div id="categorySection" class="ui-corner-all clearfix" style="clear: both;">
	<h3 class="sectionHeader courseConfigHeader">Modules</h3>
	<table id="courseconfigurationTable">
	<thead>
		<tr>
			<th></th>
			<th class="contentTextIcons"></th>
		</tr>
	</thead>
	<tbody>	</tbody>
</table>
<?= $this->fileTool; ?>
<input type="hidden" id="newImageLoad" value="Yes"/>
<input type="hidden" id="defaultLanguage" value="<?=$this->siteDefLang;?>"/>
<input type="hidden" id="langEnInt" value="<?=$this->siteEnInt;?>"/>
<input type="hidden" id="langEnUK" value="<?=$this->siteEnUK;?>"/>
</div>
