<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



echo '<div id="errorWrapper">
        <div id="errorTop">
          <p class="messageTop"><span>' . $this->sorryMsg . '</span><br>'.$this->topMsg.'</p>
        </div>
        <div id="errorBottom">
        <p class="messageBottom">' . $this->botMsg . '</p>
      </div>
      <!--- END ERROR BOTTOM SECTION --->
    </div>';

